model:
  arch: minigpt4
  model_type: pretrain_vicuna0
  max_txt_len: 160
  end_sym: "###"
  low_resource: True
  prompt_template: '###Human: {} ###Assistant: '
  ckpt: '/leonardo_work/EUHPC_D25_055/jli/MiniGPT-4/ckpt/minigpt4/prerained_minigpt4_7b.pth'


datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  okvqa:
    eval_file_path: /leonardo_work/EUHPC_D25_055/jli/dataset/okvqa/annotations/
    img_path: /leonardo_work/EUHPC_D25_055/jli/dataset/train2017/
    max_new_tokens: 20
    batch_size: 10
  vizwiz:
    eval_file_path: /leonardo_work/EUHPC_D25_055/jli/dataset/vizwiz/val.json
    img_path: /leonardo_work/EUHPC_D25_055/jli/dataset/vizwiz/vizwiz_images/
    max_new_tokens: 20
    batch_size: 10
  gqa:
    eval_file_path: /leonardo_work/EUHPC_D25_055/jli/dataset/gqa/testdev_balanced_questions.json
    img_path: /leonardo_work/EUHPC_D25_055/jli/dataset/gqa/gqa_images
    max_new_tokens: 20
    batch_size: 10

run:
  task: image_text_pretrain
  name: minigpt_evaluation
#  save_path: ./benchmark_gpt/okvqa/
#  save_path: ./benchmark_gpt/vizwiz/
  save_path: ./benchmark_gpt/gqa/
